# Generated by Django 5.1.7 on 2025-03-23 14:12

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to=core.models.pdf_upload_path)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_size", models.IntegerField(default=0)),
                ("extracted_text", models.TextField(blank=True)),
                ("extraction_completed", models.BooleanField(default=False)),
                ("extraction_error", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("summary_completed", models.BooleanField(default=False)),
                (
                    "summary_length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("summary_error", models.TextField(blank=True)),
                ("processing_time", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
